
import hljs from 'highlight.js/lib/core';

import swift from 'highlight.js/lib/languages/swift';
hljs.registerLanguage('swift', swift);
import scala from 'highlight.js/lib/languages/scala';
hljs.registerLanguage('scala', scala);
import rust from 'highlight.js/lib/languages/rust';
hljs.registerLanguage('rust', rust);
import ruby from 'highlight.js/lib/languages/ruby';
hljs.registerLanguage('ruby', ruby);
import python from 'highlight.js/lib/languages/python';
hljs.registerLanguage('python', python);
import powershell from 'highlight.js/lib/languages/powershell';
hljs.registerLanguage('powershell', powershell);
import php from 'highlight.js/lib/languages/php';
hljs.registerLanguage('php', php);
import perl from 'highlight.js/lib/languages/perl';
hljs.registerLanguage('perl', perl);
import ocaml from 'highlight.js/lib/languages/ocaml';
hljs.registerLanguage('ocaml', ocaml);
import objectivec from 'highlight.js/lib/languages/objectivec';
hljs.registerLanguage('objectivec', objectivec);
import lua from 'highlight.js/lib/languages/lua';
hljs.registerLanguage('lua', lua);
import kotlin from 'highlight.js/lib/languages/kotlin';
hljs.registerLanguage('kotlin', kotlin);
import javascript from 'highlight.js/lib/languages/javascript';
hljs.registerLanguage('javascript', javascript);
import java from 'highlight.js/lib/languages/java';
hljs.registerLanguage('java', java);
import http from 'highlight.js/lib/languages/http';
hljs.registerLanguage('http', http);
import go from 'highlight.js/lib/languages/go';
hljs.registerLanguage('go', go);
import dart from 'highlight.js/lib/languages/dart';
hljs.registerLanguage('dart', dart);
import csharp from 'highlight.js/lib/languages/csharp';
hljs.registerLanguage('csharp', csharp);
import cpp from 'highlight.js/lib/languages/cpp';
hljs.registerLanguage('cpp', cpp);
import clojure from 'highlight.js/lib/languages/clojure';
hljs.registerLanguage('clojure', clojure);
import c from 'highlight.js/lib/languages/c';
hljs.registerLanguage('c', c);
import brainfuck from 'highlight.js/lib/languages/brainfuck';
hljs.registerLanguage('brainfuck', brainfuck);
import bash from 'highlight.js/lib/languages/bash';
hljs.registerLanguage('bash', bash);
import r from 'highlight.js/lib/languages/r';
hljs.registerLanguage('r', r);

export default hljs;
